version: '3'

services:
  db:
    image: postgres:latest
    container_name: awa_keycloak_postgres_db
    restart: always
    volumes:
      - .docker/keycloak/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: awa_keycloak_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d awa_keycloak_db"]
      interval: 5s
      timeout: 5s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: awa_keycloak
    restart: always
    command: start-dev
    volumes:
      - .docker/keycloak/themes:/opt/keycloak/themes
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/awa_keycloak_db
      KC_DB_USERNAME: postgres_user
      KC_DB_PASSWORD: postgres_password
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
